### ISSUE TITLE
Test using Javascript instead of Solidity

### ISSUE THREAD

**Issue by adklempner** [urbit/constitution#1]
Testing with Solidity is uncommon, because of issues like your TestConstitution contract running out of gas, and because testing with Javascript provides more flexibility, like calling the same function from different accounts.

Also, if developers want to build a UI for your contracts, or interact with them through an existing web app, they will most likely use web3js, the same library the tests would be written in. Writing the tests in Javascript provides developers and possible auditors a great resource for understanding how your contracts work.

**Comment by Fang-** [comment]
Yeah, we've definitely run into more limitations than just the gas one. I'm planning to rewrite the tests in Javascript before we even consider putting this onto the network.

Thanks for your feedback!
