### ISSUE TITLE
in censures.sol, missing check on asClass > Class.Planet?

### ISSUE THREAD

**Issue by shrugs** [urbit/constitution#13]
on L:118

> //  only stars and galaxies may censure, and only galaxies may censure
>    //  other galaxies. (enum gets smaller for higher ship classes)

but we only check `require( whoClass >= asClass );`

does this allow a planet to censure another planet since their classes will be gte?

**Comment by Fang-** [comment]
Correct, we need an additional check there.

**Comment by Fang-** [comment]
Actually, we don't, because we only accept `uint16` as input, whereas planet addresses need at least `uint32`. A comment about this would be good to have, apparently.
