### ISSUE TITLE
question: should censures be on-chain?

### ISSUE THREAD

**Issue by shrugs** [urbit/constitution#14]
Keeping censures exclusively off-chain (i.e., only emitted via events, and then indexed by some service running on each urbit that cares about censures) would save a bit of gas. I quickly scanned the repo but didn't see external calls to `censuring` or `censoredBy`, so are features planned for using the on-chain storage?

"we want censures on-chain" is a totally valid reason to close :)

**Comment by Fang-** [comment]
> "we want censures on-chain" is a totally valid reason to close :)

Phew!

For the "let's just look at events exclusively" case, getting the current state of censures is non-trivial compared to just doing a read call. And by keeping the data on-chain we don't prevent people from taking censure stats into account in their contracts.
