### ISSUE TITLE
nit: use ships.isOwner in Constitution

### ISSUE THREAD

**Issue by shrugs** [urbit/constitution#18]
on https://github.com/urbit/constitution/blob/master/contracts/Constitution.sol#L487 we can use `ships.isOwner(_ship, old)` if I'm not mistaken

**Comment by Fang-** [comment]
That'd probably be `ships.isOwner(_ship, msg.sender)` then. But it's an additional call to/lookup in the Ships contract, which I think is a tiny bit more expensive?

**Comment by shrugs** [comment]
right, yeah `ships.isOwner(_ship, msg.sender)` 👍 

perhaps the gas savings is fine; up to you!
