### ISSUE TITLE
Worries

### ISSUE THREAD

**Issue by davidgrenier** [urbit/constitution#3]
Hello,

The choice of Eth as a platform to implement smart contracts is worrying. What are the chances you are going to get those right? What are the chances the creator of Solidity got things right?

It seems everybody and their dogs is a casuality to this shoddy programming language. To what kind of risk is Urbit exposing itself to in that choice, have you thought about the worst-case scenario?

David

**Comment by Fang-** [comment]
Hey David. Thanks for your concern!

This repo isn't really the place for discussions like these. Most long-form not-about-repo-code discussion happens on [fora](https://urbit.org/fora/), and the choice to move our PKI to Ethereum has already been extensively discussed [here](https://urbit.org/fora/posts/~2017.9.20..22.56.04..47ce~/) and [here](https://urbit.org/fora/posts/~2017.9.22..03.14.46..c207~/).

Going into this, we  realize that Ethereum isn't exactly known for its stellar development environment and idiot-proof language. Despite that, it is become our platform of choice. We are getting our smart contracts audited by [the folks behind OpenZeppelin](https://zeppelin.solutions/security-audits), and they're already [up for community review](https://github.com/urbit/constitution/) too.  
And once Urbit is mature enough, we might even be able to move the PKI back onto our own network!

**Comment by davidgrenier** [comment]
Will look up the references, much appreciated.
